{
  "id": "CVE-2024-3955",
  "sourceIdentifier": "cvd@cert.pl",
  "published": "2024-05-02T10:15:08.630",
  "lastModified": "2024-05-02T13:27:25.103",
  "vulnStatus": "Awaiting Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "URL GET parameter \"logtime\" utilized within the \"downloadlog\" function from \"cbpi/http_endpoints/http_system.py\" is subsequently passed to the \"os.system\" function in \"cbpi/controller/system_controller.py\" without prior validation allowing to execute arbitrary code.This issue affects CraftBeerPi 4: from 4.0.0.58 (commit 563fae9) before 4.4.1.a1 (commit 57572c7).\n\n"
    },
    {
      "lang": "es",
      "value": "El par\u00e1metro GET de URL \"logtime\" utilizado dentro de la funci\u00f3n \"downloadlog\" de \"cbpi/http_endpoints/http_system.py\" se pasa posteriormente a la funci\u00f3n \"os.system\" en \"cbpi/controller/system_controller.py\" sin validaci\u00f3n previa que permita ejecutar c\u00f3digo arbitrario. Este problema afecta a CraftBeerPi 4: desde 4.0.0.58 (commit 563fae9) antes de 4.4.1.a1 (commit 57572c7)."
    }
  ],
  "metrics": {},
  "weaknesses": [
    {
      "source": "cvd@cert.pl",
      "type": "Secondary",
      "description": [
        {
          "lang": "en",
          "value": "CWE-94"
        }
      ]
    }
  ],
  "references": [
    {
      "url": "https://cert.pl/en/posts/2024/05/CVE-2024-3955/",
      "source": "cvd@cert.pl"
    },
    {
      "url": "https://cert.pl/posts/2024/05/CVE-2024-3955/",
      "source": "cvd@cert.pl"
    },
    {
      "url": "https://github.com/PiBrewing/craftbeerpi4/issues/132",
      "source": "cvd@cert.pl"
    }
  ]
}